"""Add user.

Revision ID: 164338606b73
Revises: 85d5ee31654e
Create Date: 2022-09-04 10:55:24.419186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164338606b73'
down_revision = '85d5ee31654e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('persons', sa.Column('user_id', sa.Integer(), nullable=False))
    #op.create_foreign_key(None, 'persons', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'persons', type_='foreignkey')
    op.drop_column('persons', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
