"""Added cokies.

Revision ID: 525721072ace
Revises: 164338606b73
Create Date: 2022-09-04 12:04:38.268346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525721072ace'
down_revision = '164338606b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_token', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_login_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login_time')
        batch_op.drop_column('login_token')



    # ### end Alembic commands ###
