"""Added email

Revision ID: a71642e673fe
Revises: 525721072ace
Create Date: 2022-09-15 06:42:19.951481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71642e673fe'
down_revision = '525721072ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('persons', schema=None) as batch_op:
        #batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    #with op.batch_alter_table('persons', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
